### ISSUE TITLE
Error loading resource (python not found)

### ISSUE THREAD

**Issue by luisangelico** [Azure/aistudio-copilot-sample#65] opened 2023-12-11 17:52 UTC
When I run `ai init` I see the error saying that python was not found. It is in my PATH and installed. Any idea?
<img width="541" alt="ai copilot" src="https://github.com/Azure/aistudio-copilot-sample/assets/98348335/8c47e7ce-127d-46b5-a26b-93c9626e486a">
<img width="380" alt="ai copilot2" src="https://github.com/Azure/aistudio-copilot-sample/assets/98348335/23ecae40-91ce-494c-91c0-4fdc6970d1e6">

**Comment by qubitron** [comment] 2024-01-11 21:32
This may be a dupe of #67 it looks like the CLI may be throwing the wrong error message

**Closed** 2024-03-12 19:50 UTC
Labels: bug
