### ISSUE TITLE
Failed to install with 3.12.1 Python version on Windows

### ISSUE THREAD

**Issue by jhakulin** [Azure/aistudio-copilot-sample#74] opened 2024-01-22 19:56 UTC
With Python 3.12.1 version on Windows, I cannot install the requirements due to following problem:

ERROR: Failed building wheel for multidict
Failed to build multidict
ERROR: Could not build wheels for multidict, which is required to install pyproject.toml-based projects

Additional information
- Seems that multidict library is not yet supporting 3.12 version of Python. https://pypi.org/project/multidict/

Repro steps:
- Follow the sample installation instructions and face the error when running `pip install -r requirements.txt` step.

**Comment by jhakulin** [comment] 2024-01-22 20:17
Workaround for this problem is to use 3.11 version for now. However it is good to be aware and share the plan for 3.12, when it is supported.

**Comment by luigiw** [comment] 2024-02-08 18:50
I can repro this, and the root cause is actually that `azureml-dataprep` doesn't support Python 3.12.

**Comment by luigiw** [comment] 2024-02-08 18:51
@shpengmsft FYI, I assigned this to you to upgrade azureml-dataprep to support Python 3.12.

**Comment by shpengmsft** [comment] 2024-02-09 21:58
1. I'm not owner of dataprep
2. I got answer from correct owner "dataprep does not support 3.12 yet and we didn;t plan to support it immenently"

please close this issue.

**Closed** 2024-03-05 21:30 UTC

**Comment by YusakuNo1** [comment] 2024-03-05 21:33
Both `azureml-dataprep` and `azureml-metrics` are fixed to support Python 3.12, close the issue
